import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b6c8df',
        'on-secondary-fixed-variant': '#00504f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#99aaa9',
        'surface-container-high': '#e6e8ea',
        'secondary-container': '#a6f0ee',
        background: '#f7f9fb',
        error: '#ba1a1a',
        outline: '#74777d',
        tertiary: '#192929',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b6c8df',
        'on-tertiary-fixed': '#0e1e1e',
        'error-container': '#ffdad6',
        'surface-variant': '#e0e3e5',
        'tertiary-container': '#2f3f3f',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed-dim': '#b8cac9',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#c4c6cd',
        'surface-container': '#eceef0',
        'on-background': '#191c1e',
        'surface-dim': '#d8dadc',
        'on-surface-variant': '#43474c',
        'on-error': '#ffffff',
        'surface-tint': '#4f6073',
        'on-secondary-container': '#1f6f6e',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#d4e6e5',
        'inverse-surface': '#2d3133',
        primary: '#172839',
        'secondary-fixed-dim': '#8ad3d2',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#002020',
        'secondary-fixed': '#a6f0ee',
        'on-tertiary-fixed-variant': '#3a4a49',
        'primary-container': '#2d3e50',
        'on-primary-fixed': '#0a1d2d',
        'on-primary-container': '#97a9be',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1e',
        'on-primary-fixed-variant': '#37485b',
        'surface-container-lowest': '#ffffff',
        secondary: '#156968',
        'primary-fixed': '#d2e4fb',
        surface: '#f7f9fb',
        'surface-container-low': '#f2f4f6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        unit: '8px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
export default config
